project_id = "mqffqoirvbiynwrzwwse"

[functions.ai-chat]
verify_jwt = false

[functions.ai-chat-guest]
verify_jwt = false

[functions.ai-voice]
verify_jwt = false

[functions.send-event-reminder]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
