import { useState } from "react";
import { motion } from "framer-motion";
import {
    Award,
    Plus,
    Search,
    Eye,
    Trash2,
    Users,
    Calendar as CalendarIcon,
    Filter,
    Pen,
    Upload,
    Check,
} from "lucide-react";
import { AdminLayout } from "@/components/layout/AdminLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from "@/components/ui/dialog";
import { Calendar } from "@/components/ui/calendar";
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover";
import {
    useAllCertificates,
    useCertificateCategories,
    useCertificateTemplates,
    useCertificateSignatures,
    useCreateCertificate,
    useDeleteCertificate,
    useCreateSignature,
    useUpdateSignature,
    useDeleteSignature,
} from "@/hooks/useCertificates";
import { CertificateRenderer } from "@/components/certificates/CertificateRenderer";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";
import { toast } from "sonner";

export default function AdminCertificates() {
    const [activeTab, setActiveTab] = useState("certificates");
    const [isCreateOpen, setIsCreateOpen] = useState(false);
    const [isSignatureOpen, setIsSignatureOpen] = useState(false);
    const [selectedCertificate, setSelectedCertificate] = useState<any>(null);
    const [search, setSearch] = useState("");
    const [categoryFilter, setCategoryFilter] = useState("all");
    const [uploading, setUploading] = useState(false);

    // Form state for certificates
    const [formData, setFormData] = useState({
        user_id: "",
        title: "",
        description: "",
        category_id: "",
        template_id: "",
        signature_id: "",
        event_date: new Date(),
    });

    // Form state for signatures
    const [signatureData, setSignatureData] = useState({
        name: "",
        title: "",
        signature_url: "",
        is_default: false,
    });

    const { data: certificates, isLoading } = useAllCertificates({
        category: categoryFilter !== "all" ? categoryFilter : undefined,
        search: search || undefined,
    });

    const { data: categories } = useCertificateCategories();
    const { data: templates } = useCertificateTemplates();
    const { data: signatures } = useCertificateSignatures();

    // Fetch all users
    const { data: users } = useQuery({
        queryKey: ["all-users"],
        queryFn: async () => {
            const { data, error } = await supabase
                .from("profiles")
                .select("user_id, full_name, email")
                .order("full_name");

            if (error) throw error;
            return data;
        },
    });

    const createMutation = useCreateCertificate();
    const deleteMutation = useDeleteCertificate();
    const createSignatureMutation = useCreateSignature();
    const updateSignatureMutation = useUpdateSignature();
    const deleteSignatureMutation = useDeleteSignature();

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!formData.user_id || !formData.title || !formData.template_id) {
            toast.error("Please fill in all required fields");
            return;
        }

        const { data: { user } } = await supabase.auth.getUser();

        await createMutation.mutateAsync({
            ...formData,
            event_date: formData.event_date.toISOString(),
            created_by: user?.id,
            verification_code: "", // Will be auto-generated by trigger
        });

        setIsCreateOpen(false);
        resetForm();
    };

    const resetForm = () => {
        setFormData({
            user_id: "",
            title: "",
            description: "",
            category_id: "",
            template_id: "",
            signature_id: "",
            event_date: new Date(),
        });
    };

    const handleDelete = async (id: string) => {
        if (confirm("Are you sure you want to delete this certificate?")) {
            await deleteMutation.mutateAsync(id);
        }
    };

    // Signature handlers
    const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        if (!file.type.startsWith("image/")) {
            toast.error("Please upload an image file");
            return;
        }

        setUploading(true);

        try {
            const fileExt = file.name.split(".").pop();
            const fileName = `${Math.random()}.${fileExt}`;
            const filePath = `signatures/${fileName}`;

            const { error: uploadError } = await supabase.storage
                .from("certificates")
                .upload(filePath, file);

            if (uploadError) throw uploadError;

            const {
                data: { publicUrl },
            } = supabase.storage.from("certificates").getPublicUrl(filePath);

            setSignatureData({ ...signatureData, signature_url: publicUrl });
            toast.success("Signature uploaded successfully!");
        } catch (error: any) {
            toast.error(error.message || "Failed to upload signature");
        } finally {
            setUploading(false);
        }
    };

    const handleSignatureSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!signatureData.name || !signatureData.title || !signatureData.signature_url) {
            toast.error("Please fill in all fields and upload a signature");
            return;
        }

        await createSignatureMutation.mutateAsync(signatureData);
        setIsSignatureOpen(false);
        resetSignatureForm();
    };

    const handleSetDefault = async (id: string) => {
        // First, unset all defaults
        if (signatures) {
            for (const sig of signatures) {
                if (sig.is_default) {
                    await updateSignatureMutation.mutateAsync({
                        id: sig.id,
                        updates: { is_default: false },
                    });
                }
            }
        }

        // Then set the new default
        await updateSignatureMutation.mutateAsync({
            id,
            updates: { is_default: true },
        });
    };

    const handleDeleteSignature = async (id: string) => {
        if (confirm("Are you sure you want to delete this signature?")) {
            await deleteSignatureMutation.mutateAsync(id);
        }
    };

    const resetSignatureForm = () => {
        setSignatureData({
            name: "",
            title: "",
            signature_url: "",
            is_default: false,
        });
    };

    const selectedUser = users?.find((u) => u.user_id === formData.user_id);
    const selectedTemplate = templates?.find((t) => t.id === formData.template_id);

    return (
        <AdminLayout>
            <div className="space-y-8">
                {/* Header */}
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                    <div>
                        <h1 className="text-3xl font-black text-foreground tracking-tight">
                            Certificate Management
                        </h1>
                        <p className="text-muted-foreground mt-1">
                            Generate certificates and manage signatures
                        </p>
                    </div>
                    <div className="flex gap-2">
                        {activeTab === "certificates" ? (
                            <Button onClick={() => setIsCreateOpen(true)} size="lg">
                                <Plus className="w-5 h-5 mr-2" />
                                Generate Certificate
                            </Button>
                        ) : (
                            <Button onClick={() => setIsSignatureOpen(true)} size="lg">
                                <Plus className="w-5 h-5 mr-2" />
                                Add Signature
                            </Button>
                        )}
                    </div>
                </div>

                {/* Tabs */}
                <Tabs value={activeTab} onValueChange={setActiveTab}>
                    <TabsList className="grid w-full max-w-md grid-cols-2">
                        <TabsTrigger value="certificates">
                            <Award className="w-4 h-4 mr-2" />
                            Certificates
                        </TabsTrigger>
                        <TabsTrigger value="signatures">
                            <Pen className="w-4 h-4 mr-2" />
                            Signatures
                        </TabsTrigger>
                    </TabsList>

                    {/* Certificates Tab */}
                    <TabsContent value="certificates" className="space-y-4">
                        {/* Filters */}
                        <div className="flex flex-col sm:flex-row gap-4">
                            <div className="relative flex-1">
                                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                                <Input
                                    placeholder="Search certificates or users..."
                                    value={search}
                                    onChange={(e) => setSearch(e.target.value)}
                                    className="pl-10"
                                />
                            </div>
                            <Select value={categoryFilter} onValueChange={setCategoryFilter}>
                                <SelectTrigger className="w-full sm:w-[200px]">
                                    <Filter className="w-4 h-4 mr-2" />
                                    <SelectValue placeholder="All Categories" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="all">All Categories</SelectItem>
                                    {categories?.map((category) => (
                                        <SelectItem key={category.id} value={category.id}>
                                            {category.name}
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>

                        {/* Certificates List */}
                        {isLoading ? (
                            <div className="space-y-4">
                                {[1, 2, 3].map((i) => (
                                    <div key={i} className="h-24 bg-muted animate-pulse rounded-xl" />
                                ))}
                            </div>
                        ) : certificates && certificates.length > 0 ? (
                            <div className="space-y-4">
                                {certificates.map((certificate, index) => (
                                    <motion.div
                                        key={certificate.id}
                                        initial={{ opacity: 0, y: 20 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ delay: index * 0.05 }}
                                        className="bg-card border border-border rounded-xl p-6 hover:border-primary/30 hover:shadow-lg transition-all"
                                    >
                                        <div className="flex items-start justify-between">
                                            <div className="flex-1">
                                                <div className="flex items-center gap-3 mb-2">
                                                    <Award className="w-5 h-5 text-primary" />
                                                    <h3 className="font-bold text-foreground">
                                                        {certificate.title}
                                                    </h3>
                                                    {certificate.category && (
                                                        <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold">
                                                            {certificate.category.name}
                                                        </span>
                                                    )}
                                                </div>
                                                <div className="flex items-center gap-6 text-sm text-muted-foreground">
                                                    <div className="flex items-center gap-2">
                                                        <Users className="w-4 h-4" />
                                                        <span>{certificate.user?.full_name}</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <CalendarIcon className="w-4 h-4" />
                                                        <span>
                                                            {new Date(certificate.event_date).toLocaleDateString()}
                                                        </span>
                                                    </div>
                                                    <span className="font-mono text-xs">
                                                        {certificate.verification_code}
                                                    </span>
                                                </div>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <Button
                                                    variant="outline"
                                                    size="sm"
                                                    onClick={() => setSelectedCertificate(certificate)}
                                                >
                                                    <Eye className="w-4 h-4" />
                                                </Button>
                                                <Button
                                                    variant="outline"
                                                    size="sm"
                                                    onClick={() => handleDelete(certificate.id)}
                                                    className="text-destructive hover:text-destructive"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                </Button>
                                            </div>
                                        </div>
                                    </motion.div>
                                ))}
                            </div>
                        ) : (
                            <div className="text-center py-20">
                                <Award className="w-20 h-20 text-muted-foreground/30 mx-auto mb-4" />
                                <h3 className="text-xl font-bold text-foreground mb-2">
                                    No Certificates Yet
                                </h3>
                                <p className="text-muted-foreground">
                                    Start by generating your first certificate
                                </p>
                            </div>
                        )}
                    </TabsContent>

                    {/* Signatures Tab */}
                    <TabsContent value="signatures" className="space-y-6">
                        {signatures && signatures.length > 0 ? (
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                {signatures.map((signature, index) => (
                                    <motion.div
                                        key={signature.id}
                                        initial={{ opacity: 0, y: 20 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ delay: index * 0.1 }}
                                        className={`relative bg-card border rounded-xl p-6 hover:shadow-lg transition-all ${signature.is_default
                                            ? "border-primary/50 shadow-primary/10"
                                            : "border-border"
                                            }`}
                                    >
                                        {signature.is_default && (
                                            <div className="absolute top-4 right-4">
                                                <div className="px-3 py-1 rounded-full bg-primary text-primary-foreground text-xs font-bold flex items-center gap-1">
                                                    <Check className="w-3 h-3" />
                                                    Default
                                                </div>
                                            </div>
                                        )}

                                        <div className="space-y-4">
                                            {/* Signature Image */}
                                            <div className="h-24 flex items-center justify-center bg-muted/30 rounded-lg border border-border">
                                                <img
                                                    src={signature.signature_url}
                                                    alt={signature.name}
                                                    className="max-h-20 max-w-full object-contain"
                                                />
                                            </div>

                                            {/* Signature Info */}
                                            <div className="text-center">
                                                <h3 className="font-bold text-foreground">
                                                    {signature.name}
                                                </h3>
                                                <p className="text-sm text-muted-foreground">
                                                    {signature.title}
                                                </p>
                                            </div>

                                            {/* Actions */}
                                            <div className="flex gap-2">
                                                {!signature.is_default && (
                                                    <Button
                                                        variant="outline"
                                                        size="sm"
                                                        onClick={() => handleSetDefault(signature.id)}
                                                        className="flex-1"
                                                    >
                                                        <Check className="w-4 h-4 mr-2" />
                                                        Set Default
                                                    </Button>
                                                )}
                                                <Button
                                                    variant="outline"
                                                    size="sm"
                                                    onClick={() => handleDeleteSignature(signature.id)}
                                                    className="text-destructive hover:text-destructive"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                </Button>
                                            </div>
                                        </div>
                                    </motion.div>
                                ))}
                            </div>
                        ) : (
                            <div className="text-center py-20">
                                <Pen className="w-20 h-20 text-muted-foreground/30 mx-auto mb-4" />
                                <h3 className="text-xl font-bold text-foreground mb-2">
                                    No Signatures Yet
                                </h3>
                                <p className="text-muted-foreground">
                                    Add your first authorized signature
                                </p>
                            </div>
                        )}
                    </TabsContent>
                </Tabs>
            </div>

            {/* Create Certificate Dialog */}
            <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
                <DialogContent className="max-w-4xl max-h-[90vh] overflow-auto">
                    <DialogHeader>
                        <DialogTitle>Generate New Certificate</DialogTitle>
                    </DialogHeader>
                    <form onSubmit={handleSubmit} className="space-y-6">
                        <div className="grid grid-cols-2 gap-6">
                            {/* Left Column - Form */}
                            <div className="space-y-4">
                                <div>
                                    <Label htmlFor="user">Select User *</Label>
                                    <Select
                                        value={formData.user_id}
                                        onValueChange={(value) =>
                                            setFormData({ ...formData, user_id: value })
                                        }
                                    >
                                        <SelectTrigger>
                                            <SelectValue placeholder="Choose a user" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {users?.map((user) => (
                                                <SelectItem key={user.user_id} value={user.user_id}>
                                                    {user.full_name} ({user.email})
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                <div>
                                    <Label htmlFor="title">Certificate Title *</Label>
                                    <Input
                                        id="title"
                                        value={formData.title}
                                        onChange={(e) =>
                                            setFormData({ ...formData, title: e.target.value })
                                        }
                                        placeholder="e.g., First Place - Basketball Tournament"
                                    />
                                </div>

                                <div>
                                    <Label htmlFor="description">Description</Label>
                                    <Textarea
                                        id="description"
                                        value={formData.description}
                                        onChange={(e) =>
                                            setFormData({ ...formData, description: e.target.value })
                                        }
                                        placeholder="Additional details about the achievement"
                                        rows={3}
                                    />
                                </div>

                                <div>
                                    <Label htmlFor="category">Category</Label>
                                    <Select
                                        value={formData.category_id}
                                        onValueChange={(value) =>
                                            setFormData({ ...formData, category_id: value })
                                        }
                                    >
                                        <SelectTrigger>
                                            <SelectValue placeholder="Select category" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {categories?.map((category) => (
                                                <SelectItem key={category.id} value={category.id}>
                                                    {category.name}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                <div>
                                    <Label htmlFor="template">Template *</Label>
                                    <Select
                                        value={formData.template_id}
                                        onValueChange={(value) =>
                                            setFormData({ ...formData, template_id: value })
                                        }
                                    >
                                        <SelectTrigger>
                                            <SelectValue placeholder="Select template" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {templates?.map((template) => (
                                                <SelectItem key={template.id} value={template.id}>
                                                    {template.name}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                <div>
                                    <Label htmlFor="signature">Signature</Label>
                                    <Select
                                        value={formData.signature_id}
                                        onValueChange={(value) =>
                                            setFormData({ ...formData, signature_id: value })
                                        }
                                    >
                                        <SelectTrigger>
                                            <SelectValue placeholder="Select signature" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {signatures?.map((signature) => (
                                                <SelectItem key={signature.id} value={signature.id}>
                                                    {signature.name} - {signature.title}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                <div>
                                    <Label>Event Date *</Label>
                                    <Popover>
                                        <PopoverTrigger asChild>
                                            <Button
                                                variant="outline"
                                                className="w-full justify-start text-left font-normal"
                                            >
                                                <CalendarIcon className="mr-2 h-4 w-4" />
                                                {format(formData.event_date, "PPP")}
                                            </Button>
                                        </PopoverTrigger>
                                        <PopoverContent className="w-auto p-0">
                                            <Calendar
                                                mode="single"
                                                selected={formData.event_date}
                                                onSelect={(date) =>
                                                    date && setFormData({ ...formData, event_date: date })
                                                }
                                            />
                                        </PopoverContent>
                                    </Popover>
                                </div>
                            </div>

                            {/* Right Column - Preview */}
                            <div className="space-y-4">
                                <Label>Certificate Preview</Label>
                                <div className="border border-border rounded-xl p-4 bg-muted/30">
                                    {formData.user_id && formData.template_id && selectedUser ? (
                                        <div className="transform scale-[0.35] origin-top-left">
                                            <CertificateRenderer
                                                certificate={{
                                                    ...formData,
                                                    event_date: formData.event_date.toISOString(),
                                                    id: "preview",
                                                    issue_date: new Date().toISOString(),
                                                    verification_code: "PREVIEW-CODE",
                                                    created_at: new Date().toISOString(),
                                                    updated_at: new Date().toISOString(),
                                                    created_by: null,
                                                    certificate_data: null,
                                                    category: categories?.find(
                                                        (c) => c.id === formData.category_id
                                                    ),
                                                    template: selectedTemplate,
                                                    signature: signatures?.find(
                                                        (s) => s.id === formData.signature_id
                                                    ),
                                                }}
                                                userName={selectedUser.full_name}
                                            />
                                        </div>
                                    ) : (
                                        <div className="h-64 flex items-center justify-center text-muted-foreground">
                                            Fill in the form to see preview
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>

                        <DialogFooter>
                            <Button
                                type="button"
                                variant="outline"
                                onClick={() => {
                                    setIsCreateOpen(false);
                                    resetForm();
                                }}
                            >
                                Cancel
                            </Button>
                            <Button type="submit" disabled={createMutation.isPending}>
                                {createMutation.isPending ? "Generating..." : "Generate Certificate"}
                            </Button>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>

            {/* View Certificate Dialog */}
            <Dialog
                open={!!selectedCertificate}
                onOpenChange={() => setSelectedCertificate(null)}
            >
                <DialogContent className="max-w-6xl max-h-[90vh] overflow-auto">
                    <DialogHeader>
                        <DialogTitle>{selectedCertificate?.title}</DialogTitle>
                    </DialogHeader>
                    {selectedCertificate && (
                        <div className="flex justify-center bg-muted/30 p-8 rounded-xl">
                            <div className="transform scale-75 origin-top">
                                <CertificateRenderer
                                    certificate={selectedCertificate}
                                    userName={selectedCertificate.user?.full_name || ""}
                                />
                            </div>
                        </div>
                    )}
                </DialogContent>
            </Dialog>

            {/* Add Signature Dialog */}
            <Dialog open={isSignatureOpen} onOpenChange={setIsSignatureOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Add New Signature</DialogTitle>
                    </DialogHeader>
                    <form onSubmit={handleSignatureSubmit} className="space-y-4">
                        <div>
                            <Label htmlFor="sig-name">Signer Name *</Label>
                            <Input
                                id="sig-name"
                                value={signatureData.name}
                                onChange={(e) =>
                                    setSignatureData({ ...signatureData, name: e.target.value })
                                }
                                placeholder="e.g., Dr. John Doe"
                                required
                            />
                        </div>

                        <div>
                            <Label htmlFor="sig-title">Signer Title *</Label>
                            <Input
                                id="sig-title"
                                value={signatureData.title}
                                onChange={(e) =>
                                    setSignatureData({ ...signatureData, title: e.target.value })
                                }
                                placeholder="e.g., President, BCA Association"
                                required
                            />
                        </div>

                        <div>
                            <Label htmlFor="sig-upload">Signature Image *</Label>
                            <p className="text-[10px] text-muted-foreground mt-1">
                                Recommended ratio: 3:1 (e.g., 300x100px). Transparent background (PNG/WEBP).
                            </p>
                            <div className="mt-2">
                                {signatureData.signature_url ? (
                                    <div className="space-y-2">
                                        <div className="h-24 flex items-center justify-center bg-muted/30 rounded-lg border border-border">
                                            <img
                                                src={signatureData.signature_url}
                                                alt="Preview"
                                                className="max-h-20 max-w-full object-contain"
                                            />
                                        </div>
                                        <Button
                                            type="button"
                                            variant="outline"
                                            size="sm"
                                            onClick={() =>
                                                setSignatureData({ ...signatureData, signature_url: "" })
                                            }
                                        >
                                            Remove
                                        </Button>
                                    </div>
                                ) : (
                                    <div>
                                        <Input
                                            id="sig-upload"
                                            type="file"
                                            accept="image/*"
                                            onChange={handleFileUpload}
                                            disabled={uploading}
                                        />
                                        {uploading && (
                                            <p className="text-sm text-muted-foreground mt-2">
                                                Uploading...
                                            </p>
                                        )}
                                    </div>
                                )}
                            </div>
                        </div>

                        <DialogFooter>
                            <Button
                                type="button"
                                variant="outline"
                                onClick={() => {
                                    setIsSignatureOpen(false);
                                    resetSignatureForm();
                                }}
                            >
                                Cancel
                            </Button>
                            <Button
                                type="submit"
                                disabled={createSignatureMutation.isPending || uploading}
                            >
                                {createSignatureMutation.isPending ? "Adding..." : "Add Signature"}
                            </Button>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>
        </AdminLayout >
    );
}
